version: '3'
services:
  backend:
    build: ./backend
    image: taskdockfinal-backend
    ports:
      - "5001:5001"
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5050:5000"   
    depends_on:
      - backend
  
volumes:
    backend_data:
